version: 0.2

phases:
  install:
    run-as: root
    on-failure: ABORT
    commands:
      - apk add py3-pip
      - pip3 install --upgrade pip && pip3 install --upgrade setuptools
      - pip3 install checkov
  build:
    commands:
      - cd ${TERRAFORM_PATH}
      - checkov -d . --download-external-modules true